AllCops:
  Exclude:
    - "bin/**/*"
    - ".git/**/*"
    - "test/dummy/**/*"
    - "test/tmp/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/SlicingWithRange:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantParentheses:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SafeNavigation:
  Enabled: true
  Exclude:
    - "/app/views/**/*.slim"
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/MultilineBlockLayout:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Bundler/OrderedGems:
  Enabled: false

# Relaxed.Ruby.Style
## Version 2.5

Style/Alias:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylealias

Style/AsciiComments:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleasciicomments

Style/BeginBlock:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylebeginblock

Style/BlockDelimiters:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleblockdelimiters

Style/CommentAnnotation:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylecommentannotation

Style/DoubleNegation:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styledoublenegation

Style/EndBlock:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleendblock

Style/FormatString:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleformatstring

Style/IfUnlessModifier:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleifunlessmodifier

Style/Lambda:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylelambda

Style/ModuleFunction:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylemodulefunction

Style/MultilineBlockChain:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylemultilineblockchain

Style/NegatedIf:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylenegatedif

Style/NegatedWhile:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylenegatedwhile

Style/NumericPredicate:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylenumericpredicate

Style/ParallelAssignment:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleparallelassignment

Style/PercentLiteralDelimiters:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylepercentliteraldelimiters

Style/PerlBackrefs:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleperlbackrefs

Style/Semicolon:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesemicolon

Style/SignalException:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesignalexception

Style/SingleLineBlockParams:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesinglelineblockparams

Style/SingleLineMethods:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesinglelinemethods

Style/SpecialGlobalVars:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylespecialglobalvars

Style/TrailingCommaInArguments:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styletrailingcommainarguments

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styletrailingcommainarrayliteral

Style/TrailingCommaInHashLiteral:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styletrailingcommainhashliteral

Style/SymbolArray:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesymbolarray

Style/WhileUntilModifier:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylewhileuntilmodifier

Style/WordArray:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylewordarray

Layout/DotPosition:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#layoutdotposition

Layout/SpaceBeforeBlockBraces:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#layoutspacebeforeblockbraces

Layout/SpaceInsideParens:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#layoutspaceinsideparens

Lint/AmbiguousRegexpLiteral:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#lintambiguousregexpliteral

Lint/AssignmentInCondition:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#lintassignmentincondition

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics:
  Enabled: false
